[project]
name = "pycandle-spy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "packaging",
    "safetensors",
    "torch>=2.0.0",
    "onnx",
    "onnx2torch",
    "onnxscript",
]
